### ISSUE TITLE
support: missing dependency on robotiq_c_model_visualization

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial-attic/hilgendorf#3]
This leads to errors when trying to load the xacro on systems that don't have it installed.

**Comment by Jmeyer1292** [comment]
@gavanderhoorn The gripper visualization and the name of the corresponding package is in flux at the moment. I was waiting till I knew if the pull-request against the main Robotiq repo would go through.

Would it be a better idea to just copy and paste the required visualization components into this repository for this project alone?

**Comment by gavanderhoorn** [comment]
No, waiting is fine. imo, as this is an FTP (and not yet a publicly released repository), not having a one-click install is fine at the moment.

I just wanted to report the issue. Let's wait till the `robotiq` PRs are merged.
