### ISSUE TITLE
Add Hilgendorf CAD Model or Rviz Model to README

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-attic/hilgendorf#4]
Add an image to the repo README file so that people can see what the robot configuration looks like.

**Comment by Jmeyer1292** [comment]
Something ala: 
![hilgendorf](https://cloud.githubusercontent.com/assets/4960180/5909930/9f47ad10-a57a-11e4-9408-59f751c67df7.JPG)
?

**Comment by shaun-edwards** [comment]
Yep.

**Comment by Jmeyer1292** [comment]
I recommend this be closed.
