### ISSUE TITLE
Both arms use the same action server

### ISSUE THREAD

**Issue by garyedwards** [ros-industrial-attic/hilgendorf#5]
Hi

Both the ur drivers seem to be set up to subscribe to one action server in the example files.  This seems to run fine except every time you send a message for one arm the other's driver gives an error as the joint names are incorrect for it.

Should each have its open set of "/follow_joint_trajectory" topics or am I missing something in how this should function?

This the code I am using to test with:  https://s3-eu-west-1.amazonaws.com/data.re.je/twins_move.py

Thanks for any tips.

**Comment by shaun-edwards** [comment]
@Jmeyer1292 , please address

**Comment by Jmeyer1292** [comment]
I'll get on it ASAP.

**Comment by Jmeyer1292** [comment]
@garyedwards Hey, sorry about the issue. If you have a chance, could you test out the pull request I just put up #6? I'd appreciate it.

**Comment by garyedwards** [comment]
Thanks @Jmeyer1292 I should be able to test first thing tomorrow and will report back.

**Comment by garyedwards** [comment]
I have done some tests with the "robot_interface_streaming_hilgendorf.launch" file and things seem to be working much better with the separate servers.  I will let you know if I find any further issues.
